//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRSalary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BI_City()
        {
            this.BI_Personel = new HashSet<BI_Personel>();
        }
    
        public long City_ID { get; set; }
        public string Name { get; set; }
        public long Entitycode { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BI_Personel> BI_Personel { get; set; }
    }
}
