//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRSalary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Condition
    {
        public long Condition_ID { get; set; }
        public string Name { get; set; }
        public long Entitycode { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
