//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRSalary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Personel
    {
        public long Personel_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> PersoneliCode { get; set; }
        public string NationalCode { get; set; }
        public long Company_ID { get; set; }
        public long Project_ID { get; set; }
        public long City_ID { get; set; }
        public string CreditCard { get; set; }
        public string AccountNumber { get; set; }
        public string CardNumber { get; set; }
        public string ValidBoss { get; set; }
        public Nullable<long> FixMoney { get; set; }
        public string Station { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual BI_City BI_City { get; set; }
        public virtual BI_Company BI_Company { get; set; }
        public virtual BI_Project BI_Project { get; set; }
    }
}
